### ISSUE TITLE
bug: KeyError in langchain callback in on_llm_error

### ISSUE THREAD

**Issue by pcoccoli** [langfuse/langfuse#5188]
### Describe the bug

langfuse==2.51.5

From my logs:

```
2025-01-23T19:17:41.497Z        error   Error raised by bedrock service: An error occurred (ThrottlingException) when calling the InvokeModel operation (reached max retries: 4): Too many requests, please wait before trying again.
2025-01-23T19:17:41.500Z        error   UUID('9df62b91-8248-4319-b874-ff639a65b03c')
UUID('9df62b91-8248-4319-b874-ff639a65b03c')
  File "/venv/lib/python3.12/site-packages/langfuse/callback/langchain.py", line 863, in on_llm_error
    self.runs[run_id] = self.runs[run_id].end(
                        ~~~~~~~~~^^^^^^^^
```

`self.runs` appears to be a dict initialized as `self.runs = {}`. Presumably there is no run for this since we hit a ThrottlingException (from boto3) when calling Bedrock InvokeModel.

[#1078](https://github.com/langfuse/langfuse/issues/1078) adds a check before accessing `self.runs[run_id]` but only in `on_chain_error`. There is no such check in `on_llm_error`.

That line is now here: [https://github.com/langfuse/langfuse-python/blob/2a0964c64e5b1149ee3a667bf7c6da3b703ccbec/langfuse/callback/langchain.py#L900](https://github.com/langfuse/langfuse-python/blob/2a0964c64e5b1149ee3a667bf7c6da3b703ccbec/langfuse/callback/langchain.py#L900)

Potentially similar issues are:

* [#3296](https://linear.app/langfuse/issue/LFE-2096/bug-langfuse-run-not-found-in-on-chain-ned-with-langchain)
* [#2155](https://linear.app/langfuse/issue/LFE-1261/bug-run-not-found-and-generations-are-not-stacked-under-span)j
* [#1927](https://github.com/langfuse/langfuse/issues/1927)

### To reproduce

Exceed the throttling limit for a Bedrock model in AWS

### SDK and container versions

*No response*

### Additional information

*No response*

### Are you interested to contribute a fix for this bug?

No

**Comment by hassiebp** [comment]
@pcoccoli Thanks for raising this - could you explain in what circumstances you are seeing this error exactly? Does it occur every time Bedrock fails in your chain or only occasionally?

**Comment by pcoccoli** [comment]
It occurs every time I see a throttling exception from Bedrock, i.e. calling `invoke` on langchain_aws's `ChatBedrock` with the callback set to `langfuse_context.get_current_langchain_handler()`.
Is there any reason to believe that `self.runs` should never raise `KeyError`?  I haven't had time to audit the code, but I see that most of the `on_...` functions do check `if run_id not in self.runs:` and raise if not (though all this really does is change the exception type).

**Comment by hassiebp** [comment]
@pcoccoli I have linked a PR to add a safeguard for your error case. 

As for the error stack below, it seems like the event upload has failed on shutdown. Have you configured your keys correctly?

**Comment by pcoccoli** [comment]
The "unexpected error" only happens after I've seen the run_id KeyError (which only happens when I hit AWS rate limits), and I only see that stack trace on shutdown.  I have not had time to reproduce it.
During normal operations, traces are uploading just fine.

**Comment by hassiebp** [comment]
@pcoccoli - got it, the fix was released yesterday, please upgrade and let us know if you experience this issue again! 🙏🏾

**Comment by pcoccoli** [comment]
Thanks for the fix; it looks like it only went into 3.x though?  If so, I'm not able to test until we migrate.
I may be able to patch locally in test environment in the meantime.

**Comment by pcoccoli** [comment]
Ah; my bad.  I confused the langfuse version with the python SDK version.

The KeyError is gone, and (perhaps coincidentally, still not sure) the hang on shutdown is also gone.

**Comment by hassiebp** [comment]
Thanks for letting us know! 🙏🏾
