### ISSUE TITLE
feat: Allow manual configuration of the shadowDatabase

### ISSUE THREAD

**Issue by Kola50011** [langfuse/langfuse#738]
### Describe the feature you'd like to request

> The shadow database is a second, temporary database that is created and deleted automatically* each time you run prisma migrate dev and is primarily used to detect problems such as schema drift or potential data loss of the generated migration.

When using a cloud-hosted database for langfuse the user might not have the permission to "CREATE DATABASE". This is needed to run the migrations. We would like to create the database manually and configure the "SHADOW_DATABASE_URL". This way we can run langfuse without using a superuser in the database.

### Describe the solution you'd like to see

Add a new environment variable SHADOW_DATABASE_URL to langfuse and plug it into the datasource configuration.

### Additional information

* [Cloud-hosted shadow databases must be created manually](https://www.prisma.io/docs/orm/prisma-migrate/understanding-prisma-migrate/shadow-database#cloud-hosted-shadow-databases-must-be-created-manually)
* [Datasource configuration](https://github.com/langfuse/langfuse/blob/main/prisma/schema.prisma#L9-L13)

### Contribute

- [ ] Yes, I can implement this and raise a PR

**Comment by marcklingen** [comment]
Thanks for raising this.

Context: on Langfuse cloud, we use  two envs:
- DIRECT_URL for migrations
- DATABASE_URL: usual operations, we use pgbouncer for scalability

Dockerized: in entrypoint.sh DIRECT_URL is set to DATABASE_URL as that's the easier configuration for most users.

**Comment by marcklingen** [comment]
@Kola50011 I just released DIRECT_URL in v1.21.0. Can you check whether this solves the issue for you?

**Comment by Kola50011** [comment]
@marcklingen 

Hey, no this doesn't fix our issue. The user specified in the DATABASE_URL / DIRECT_URL does not have the permissions to create a new database or schema (company policy). Therefore, we get the following error:

> Error: Schema engine error:
   ERROR: permission denied to create database

We need to set a separate url to the shadow database so that prisma can generate the diff between the new and old database schema.

We are using [Cloud SQL](https://cloud.google.com/sql) from Google.

**Comment by marcklingen** [comment]
Allright, thanks for the context, I'll add this soon and ping you once it's merged

**Comment by marcklingen** [comment]
@Kola50011, released this in https://github.com/langfuse/langfuse/releases/tag/v1.22.0
