### ISSUE TITLE
bug: span.update overwrites trace when span has trace_context

### ISSUE THREAD

**Issue by Henni16** [langfuse/langfuse#8185]
### Describe the bug

When passing a trace_context to the `start_as_current_span` method the `update` method of the span updates both the span itself and the trace.
I am not 100% sure this is a bug, but due to the existence of the `update_trace` method it does look unintended.

### To reproduce

```python
from langfuse import get_client

client = get_client()
with client.start_as_current_span(name="span name", trace_context={"trace_id": ...}) as span:
   span.update(input="should not be top level", name="span name")
   span.update_trace(output="output of trace")
```

This code will result in:
1. a trace with the name "span name" and both input and output set
2. a span inside the trace with the same name and input but no output

### SDK and container versions

Langfuse Backend: 3.86.0
Python SDK: 3.2.1

### Are you interested to contribute a fix for this bug?

No

**Comment by hassiebp** [comment]
Thanks for raising this! This is fixed in our latest platform image

**Comment by Henni16** [comment]
Thank you for the update. Could you please let me know which version includes the fix? I'm currently using backend version 3.98.2 and sdk version 3.2.7, but I’m still experiencing the issue.

**Comment by hassiebp** [comment]
@Henni16 Here's the resulting trace from this code, which looks to me as expected 🤔  Were you expecting anything different?

```python
from langfuse import get_client

client = get_client()

with client.start_as_current_span(
    name="span name", trace_context={"trace_id": get_client().create_trace_id()}
) as span:
    span.update(input="should not be top level", name="span name")
    span.update_trace(output="output of trace")

```
https://cloud.langfuse.com/project/cm1geuvsr027w7nuhw8g69xtb/traces/556681df26f9fdd9bde107443497254b?timestamp=2025-08-18T13:47:09.620Z&display=details

**Comment by Henni16** [comment]
The trace you provided now has the name "span name" and the input "should not be top level".
I would have expected two things:
- the trace has no name, as we did not set one
- the input of the trace to be empty

Currently, the `update` method of a span still seems to update the trace. I would expect only the `update_trace` method to do so.

The reason this is important for me is, that we have a multi-step process across multiple services. Each service starts a span with the given trace_id.
I would like to set a trace name and input at the start of this process and never touch it again. Currently, the trace always has the name and input of the very last span that I'm starting with the trace_id.

Basically, what we're doing is start the process with:

```python
client = get_client()
with client.start_as_current_span(name="",trace_context={"trace_id": ...}) as span:
    span.update_trace(name="My little process", input="input of whole process")
```

And then multiple steps that look like this:

```python
with client.start_as_current_span(name="", trace_context={"trace_id": trace_id}) as span:
    span.update(name="some process step", input="input of this particular step")
    some_processing_here()
```

All of our traces are now called "some process step" and have the input "input of this particular step".

**Comment by hassiebp** [comment]
@Henni16 When setting `trace_context`, the span will be treated as a root span and thus the span input / output / metadata / name will be propagated to the trace. 

How exactly are you orchestrating your different services? As per our docs, it is recommended to rely on OTEL native trace context propagation as much as you can to avoid these side effects of using trace_context. https://langfuse.com/docs/observability/sdk/python/sdk-v3#distributed-tracing

**Comment by Henni16** [comment]
Each service is running in its own kubernetes pod. They receive messages containing an input the trace_id.
It's ok for the span to be a root span. However, I still don't understand why a method named `update` called on a span updates the trace when there is an explicit `update_trace` method.
